apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:	          # 这是关于该 Service 的定义，描述了 Service 如何选择 Pod，如何被访问
  selector:	    # 标签选择器
    app: nginx	# 选择包含标签 app:nginx 的 Pod
  ports:
  - name: nginx-port	# 端口的名字
    protocol: TCP	    # 协议类型 TCP/UDP
    port: 8081	      # 集群内的其他容器组(Pod)可通过 8081 端口访问 Service
    nodePort: 30010   # 通过任意节点的 30010 端口访问 Service
    targetPort: 80	  # 将请求转发到匹配 Pod 的 80 端口
  type: NodePort	    # Serive的类型，ClusterIP/ NodePort/ LoaderBalancer


# 需要一种机制，为前端系统屏蔽后端系统的 Pod（容器组）在销毁、创建过程中所带来的 IP 地址的变化
# Service（服务）使 Pod（容器组）之间的相互依赖解耦
# 所谓滚动更新就是 使用新的镜像逐步替代同名deployment 下的 Pod
# master节点包括用来创建和复制Pod的Replication Controller
# 以及 API Server提供可以用来和集群交互的REST端点

# Kubelet：是主节点代理。
# Kube-proxy：Service使用其将链接路由到Pod
# master 会为Service创建一个本地集群的DNS入口