apiVersion: v1
kind: Pod
metadata:
  name: marvin-backend
  labels:
    app: marvin
    version: "0.5"
    role: backend

spec:
  nodeSelector:
    kubernetes.io/hostname: laojun

  imagePullSecrets:
  - name: nitrogen-harbor

  volumes:
  - name: nfs
    nfs:
      server: 192.168.1.179
      path: /data/nfs/marvin/

  containers:
  - name: backend
    imagePullPolicy: IfNotPresent
    image: harbor.atompai.com/xet/marvin/backend:base
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    workingDir: /home/xarc-marvin/
    volumeMounts:
    - mountPath: /data/static/
      subPath: static/
      name: nfs
    - mountPath: /data/logs/
      subPath: logs/backend/
      name: nfs
    ports:
    - containerPort: 8080
      protocol: TCP
      name: backend-port
      hostPort: 8080
    env:
    - name: WEBAPP_ENV
      value: dev
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 4
        memory: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: marvin-deployment
    namespace: leilei-hou

spec:
    replicas: 1
    selector:
     matchLabels:
       app: marvin-pod

    template:
      metadata:
        name: marvin-pod-template
        labels:
          app: marvin-pod

      spec:
        imagePullSecrets:
        - name: nitrogen-harbor

        # Volume's name. Must be a DNS_LABEL and unique within the pod
        volumes:
        - name: nfs
          nfs:
            server: 192.168.1.179
            path: /data/nfs/marvin/

        containers:
        - name: mysql
          imagePullPolicy: IfNotPresent
          image: harbor.atompai.com/xet/marvin:data
          volumeMounts:
          - mountPath: /var/lib/mysql/
            subPath: mysql/
            name: nfs
          ports:
          - containerPort: 3306
            protocol: TCP
            name: mysql-port

        - name: backend
          imagePullPolicy: IfNotPresent
          image: harbor.atompai.com/xet/marvin/backend:base
          command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
          workingDir: /home/xarc-marvin/
          volumeMounts:
          - mountPath: /data/static/
            subPath: static/
            name: nfs
          - mountPath: /data/logs/
            subPath: logs/backend/
            name: nfs
          ports:
          - containerPort: 8080
            protocol: TCP
            name: backend-port
          env:
          - name: WEBAPP_ENV
            value: dev

        - name: frontend
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          workingDir: /home/xarc-marvin/
          volumeMounts:
          - mountPath: /data/static/
            subPath: static/
            readOnly: true
            name: nfs
          - mountPath: /data/logs/
            subPath: logs/frontend/
            name: nfs
          ports:
          - containerPort: 80
            name: frontend-port
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: marvin-service
  namespace: leilei-hou
spec:
  selector:
    app: marvin-pod
  type: NodePort
  ports:
  - name: nginx
    port: 6060
    targetPort: 80
    nodePort: 30080
